platform :ios, '8.3'
pod 'SVProgressHUD', '1.1.2'
pod 'AFNetworking' 
pod 'BButton'
pod 'CrittercismSDK'
pod 'kingpin'
pod 'RHManagedObject', :path => '../RHManagedObject/'
# pod 'RHManagedObject'
pod 'RHTools', :path => '../RHTools/'
# pod 'RHTools', :git => 'https://github.com/chriscdn/RHTools.git'
pod 'ECSlidingViewController'
pod 'Lockbox'
pod 'MBAutoGrowingTextView', '~> 0.1.0'
